# Template Version
AWSTemplateFormatVersion: '2010-09-09'
# Description Service
Description: AWS CloudFormation Create S3 bucket
# Resources to Deploy
Resources:
  # Resources name
  S3BucketResource:
    # Resource Type
    Type: 'AWS::S3::Bucket'
    # Properties Deploy Service
    Properties:
      AccessControl: PublicRead
      BucketName: tv-s3-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: S3-Bucket-WebApp
  S3BucketPolicyResource:
    Type: AWS::S3::BucketPolicy
    Properties:
      # The name of the Amazon S3 Bucket to which the policy applies
      Bucket: !Ref 'S3BucketResource'
      # A policy document containing permissions to add to the specified Bucket
      PolicyDocument:
        Statement:
          -
            # For each resource, specified the operations that will allow (or deny)
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            # What the effect will be when the user request the specific ations (could be allow or deny)
            Effect: "Allow"
            Resource: !Join ['', ['arn:aws:s3:::', 'tv-s3-bucket', '/*']]
            Principal:
              AWS: "*"